language: node_js
node_js:
- '8'
cache: yarn
env:
  global:
  - GH_REF: github.com/ingoclaro/ReDoc.git
  - GIT_AUTHOR_EMAIL: bot@users.noreply.github.com
  - GIT_AUTHOR_NAME: Bot
addons:
  chrome: stable
before_script: npm run bundle && npm run compile:cli
script: npm test && npm run e2e
after_script: cat ./coverage/lcov.info | coveralls
before_deploy: npm run compile:cli
deploy:
  matrix:
  - provider: npm
    skip_cleanup: true
    email: ingoclaro@gmail.com
    tag: next
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: cd cli && yarn install && yarn ci-publish || true
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: yarn deploy:demo
  api_key:
    secure: e+vllOURMDUdM9RKQe0qjbqmvMI2vaY2SeesqEUU5e1mvVg7ajN8kIPTGgAZt/sOWacGm5fFFKWVw6zU0qMbvGTi9FVZb+D6fsq1YmmGROv2fOc3NXX+LXr8YayfSjgrSgCSsCf+Pojasq1E/hc6V3sl8qz3H6TFHim/WHqkBBTkfDraCqNGji4/WD+4Pj2ziseRfmnytFWZJL5U5e2RIBMh8nbSrlo1v0kQzuFyaZeFll4WyU4u6r/xSwAguCg/QPbo55g8kigDFSU255A1GdJq29tJDKbZyTSGt60gwReyPJleLKpoMM8ME4eNFTTsaHyCKoQkoFc1Ncv6elITYzkYxoCa2AbO0izoF9+pE45J+1fzahZGzPWvBvohX53ItCc12EZU35szhUytcDzOl66bwYtIZfSNKy7VXp7FIyWULBZCLrPIAHq7vt/2jX6aT7+69eLm7LR4iOHMtUS976cA0nC4CvIJWQoRg+DADtpGHxIx78cTk1c218fKmgXcf0hUvSuolLUt/HKAZ5iieTGPa+RbIPOssCZ3b45Lw08cnV0LjClTGzXmz9HwqP6yDKjaqn9Fe3+OLw/RYWN/0VKykmETD+R//0EEWiX0KYFj+WhwA2coZng/jtXZwgV/qOjTRmegz3B+DbOBNIkMeThhVfHZ8NotvrT7NM6xlVE=
